ADOP 210 change
hmcts/adoption-web pull request #122
Opened 2022-01-19 13:41 UTC by pankajhmcts

### Change description
Implementation of first two screen.

### JIRA link
https://tools.hmcts.net/jira/browse/ADOP-210

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [X ] No

2022-01-19 14:28 UTC, abidfs commented on src/main/steps/children/adoption-agency/content.ts
> +  adopAgencyEmail: 'Email address of your contact',
```suggestion
  adopAgencyContactEmail: 'Email address of your contact',
```

2022-01-19 14:29 UTC, abidfs commented on src/main/steps/children/adoption-agency/content.ts
> +  adopAgencyEmail: 'Email address of your contact (in Welsh)',
```suggestion
  adopAgencyContactEmail: 'Email address of your contact (in Welsh)',
```

2022-01-19 14:30 UTC, abidfs commented on src/main/steps/children/adoption-agency/get.ts
> +      console.log('req.query.add 14: ' + req.query.add);
Remove unwanted console statements

2022-01-19 14:30 UTC, abidfs commented on src/main/steps/children/adoption-agency/get.ts
> +    //else if (req.query.change) {
remove commented code

2022-01-19 14:31 UTC, abidfs commented on src/main/steps/children/adoption-agency/get.ts
> +import autobind from 'autobind-decorator';
Unit test not covered for this file

2022-01-19 14:32 UTC, abidfs commented on src/main/steps/children/adoption-agency/post.test.ts
> +// const mockGetParsedBody = jest.fn();
Unit tests missing

2022-01-19 14:34 UTC, abidfs commented on src/main/steps/children/childrenSequence.test.ts
> +    expect(childrenSequence).toHaveLength(13);
missing expect for newly added objects in sequence

2022-01-19 14:34 UTC, abidfs commented on src/main/steps/children/other-adoption-agency/content.ts
> +  no: 'No',
yes and no are already declared in common content, you can remove it

2022-01-19 14:34 UTC, abidfs commented on src/main/steps/children/other-adoption-agency/content.ts
> +  no: 'No (in Welsh)',
yes and no are already declared in common content, you can remove it

2022-01-19 14:35 UTC, abidfs commented on src/main/steps/children/other-adoption-agency/content.ts
> +  title: 'Was there another adoption agency or local authority involved in placing the child?',
Please make it label
```suggestion
  label: 'Was there another adoption agency or local authority involved in placing the child?',
```

2022-01-19 14:35 UTC, abidfs commented on src/main/steps/children/other-adoption-agency/content.ts
> +  title: 'Was there another adoption agency or local authority involved in placing the child? (in Welsh)',
same as english

2022-01-19 14:37 UTC, abidfs requested changes
looks good but few minor comments

2022-01-21 21:48 UTC, abidfs commented on src/main/steps/children/adoption-agency/get.test.ts
> +            selectedAdoptionAgencyId: 'MOCK_PLACEMENT_ORDER_ID',
Can you please remove placement order references from this file

2022-01-21 21:49 UTC, abidfs commented on src/main/steps/children/adoption-agency/get.ts
> +      console.log('req.query.add 14: ' + req.query.add);
I see you resolved the conversation but did not remove the console log

2022-01-21 21:49 UTC, abidfs commented on src/main/steps/children/adoption-agency/get.ts
> +    console.log('get 38 ' + req.session.userCase.selectedAdoptionAgencyId);
same here, please remove console log

2022-01-21 21:51 UTC, abidfs commented on src/main/steps/children/childrenSequence.test.ts
> +    ).toBe('/children/other-adoption-agency');
need to cover other scenarios as well

2022-01-21 21:51 UTC, abidfs commented on src/main/steps/children/childrenSequence.test.ts
> +    expect(childrenSequence[12].getNextStep({ hasAnotherAdopAgencyOrLA: YesOrNo.NO })).toBe('/task-list');
need to cover other scenarios as well
see the jest coverage report for more details

2022-01-21 21:51 UTC, abidfs commented on src/main/steps/children/childrenSequence.ts
> +        : Urls.OTHER_ADOPTION_AGENCY,
unit tests not covered for all scenarios

2022-01-21 21:52 UTC, abidfs commented on src/main/steps/children/childrenSequence.ts
> +        : `${Urls.ADOPTION_AGENCY}?change=${userCase.adopAgencyOrLAs![1].adopAgencyOrLaId}`,
unit tests not covered for all scenarios

2022-01-21 21:53 UTC, abidfs commented on src/main/steps/task-list/content.ts
> +};
as discussed, please move this method to task-list > utils.ts file
also cover the unit tests for the same

2022-01-21 21:54 UTC, abidfs commented on src/test/e2e/pages/taskList.page.js
> +    adoptionAgencyDetailsStatus: 'strong[id$="birth-father-status"]',
I think the id is wrong it shouldn't be "birth-father-status"

2022-01-21 21:55 UTC, abidfs requested changes
few minor changes needed

2022-01-24 15:30 UTC, abidfs submitted a review, later dismissed
Approving it but I think `getAdoptionAgencyDetailStatus` logic can be improved
up to you

2022-01-24 21:13 UTC, nraghu32 approved these changes

2022-01-24 21:13 UTC, merged