Adop 560 eligibility content update
hmcts/adoption-web pull request #213
Opened 2022-02-24 11:59 UTC by dilipsamrahmcts

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

https://tools.hmcts.net/jira/browse/ADOP-560
https://tools.hmcts.net/jira/browse/ADOP-554

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [ ] No

2022-02-24 14:04 UTC, abidfs commented on src/main/steps/eligibility/domicile/content.test.ts
> +    expect(generatedContent.errors).toEqual(enContent.errors);
can be simplified using languageAssertions
example https://github.com/hmcts/adoption-web/blob/05ddc4ab44fa2e4bee1632469dc6df594ee7ca22/src/main/steps/sibling/placement-order-check-your-answers/content.test.ts#L51

2022-02-24 14:05 UTC, abidfs commented on src/main/steps/eligibility/domicile/content.test.ts
> +    expect(generatedContent.errors).toEqual(cyContent.errors);
https://github.com/hmcts/adoption-web/blob/05ddc4ab44fa2e4bee1632469dc6df594ee7ca22/src/main/steps/sibling/placement-order-check-your-answers/content.test.ts#L51

2022-02-24 14:05 UTC, abidfs commented on src/main/steps/eligibility/domicile/content.ts
> +            `<p class="govuk-label">${l.domicileNo}</p> <p class ="govuk-label"><a href="https://www.gov.uk/child-adoption">${l.moreInfo}</a></p>`,
```suggestion
            `<p class="govuk-label">${l.domicileNo}</p> <p class="govuk-label"><a href="https://www.gov.uk/child-adoption">${l.moreInfo}</a></p>`,
```

2022-02-24 14:06 UTC, abidfs commented on src/main/steps/eligibility/lived-uk/content.test.ts
> +    expect(generatedContent.errors).toEqual(enContent.errors);
whilst you are here, can you simplify this using https://github.com/hmcts/adoption-web/blob/05ddc4ab44fa2e4bee1632469dc6df594ee7ca22/src/main/steps/sibling/placement-order-check-your-answers/content.test.ts#L51

2022-02-24 14:07 UTC, abidfs commented on src/main/steps/eligibility/lived-uk/content.ts
> +            `<p class="govuk-label">${l.livedUKNo}</p> <p class ="govuk-label"><a href="https://www.gov.uk/child-adoption">${l.moreInfo}</a></p>`,
```suggestion
            `<p class="govuk-label">${l.livedUKNo}</p> <p class="govuk-label"><a href="https://www.gov.uk/child-adoption">${l.moreInfo}</a></p>`,
```

2022-02-24 14:07 UTC, abidfs commented on src/main/steps/eligibility/under-18/content.test.ts
> +    expect(generatedContent.errors).toEqual(enContent.errors);
same as above comments

2022-02-24 14:07 UTC, abidfs commented on src/main/steps/eligibility/under-18/content.test.ts
> +    expect(generatedContent.errors).toEqual(cyContent.errors);
same as above comments

2022-02-24 14:07 UTC, abidfs commented on src/main/steps/eligibility/under-18/content.ts
> +            `<p class="govuk-label">${l.under18No}</p> <p class ="govuk-label"><a href="https://www.gov.uk/child-adoption">${l.moreInfo}</a></p>`,
```suggestion
            `<p class="govuk-label">${l.under18No}</p> <p class="govuk-label"><a href="https://www.gov.uk/child-adoption">${l.moreInfo}</a></p>`,
```

2022-02-24 14:08 UTC, abidfs commented on src/main/steps/eligibility/under-21/content.test.ts
> +    expect(generatedContent.errors).toEqual(enContent.errors);
same as above

2022-02-24 14:08 UTC, abidfs commented on src/main/steps/eligibility/under-21/content.test.ts
> +    expect(generatedContent.errors).toEqual(cyContent.errors);
same as above

2022-02-24 14:08 UTC, abidfs commented on src/main/steps/eligibility/under-21/content.ts
> +            `<p class="govuk-label">${l.under21Yes}</p> <p class ="govuk-label"><a href="https://www.gov.uk/child-adoption">${l.moreInfo}</a></p>`,
```suggestion
            `<p class="govuk-label">${l.under21Yes}</p> <p class="govuk-label"><a href="https://www.gov.uk/child-adoption">${l.moreInfo}</a></p>`,
```

2022-02-24 14:09 UTC, abidfs requested changes
need to fix few typos

2022-02-24 15:17 UTC, abidfs approved these changes

2022-02-25 11:40 UTC, pankajhmcts approved these changes

2022-02-25 11:42 UTC, pankajhmcts commented
@dilipsamrahmcts @nraghu32 @gauravtomar-gh @abidfs 
Merging this PR after testing complete confirmation received.

2022-02-25 11:43 UTC, merged