Adop 415 error handling
hmcts/adoption-web pull request #272
Opened 2022-03-11 10:41 UTC by dilipsamrahmcts

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

https://tools.hmcts.net/jira/browse/ADOP-415

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [ ] No

2022-03-11 12:07 UTC, abidfs commented on src/main/steps/error/error.njk
> +    {% endif %}
alignment is incorrect

2022-03-11 12:08 UTC, abidfs commented on src/main/steps/error/error.njk
> +    {% if StatusCodes === StatusCodes.NOT_FOUND %}
```suggestion
    {% if statusCode === StatusCodes.NOT_FOUND %}
```

2022-03-11 12:08 UTC, abidfs commented on src/main/steps/error/error.njk
> +    {% if StatusCodes === StatusCodes.INTERNAL_SERVER_ERROR %}
```suggestion
    {% if statusCode === StatusCodes.INTERNAL_SERVER_ERROR %}
```

2022-03-11 12:09 UTC, abidfs requested changes
minor changes needed

2022-03-28 11:06 UTC, pankajhmcts approved these changes

2022-03-28 11:55 UTC, abidfs approved these changes

2022-03-28 11:55 UTC, merged