E2 e negative
hmcts/adoption-web pull request #458
Opened 2022-05-13 14:20 UTC by Shilpa-Krishna

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### Change description

### JIRA link

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [ ] No

2022-05-16 11:42 UTC, abidfs commented on src/test/config.ts
> +import { getTokenFromApi } from '../main/app/auth/service/get-service-auth-token';
This is not required

2022-05-16 11:45 UTC, abidfs requested changes
just few bits to change before merging this PR
see comments

2022-05-16 11:45 UTC, abidfs commented on src/test/config.ts
> +const idamUserManager = new IdamUserManager(sysConfig.get('services.idam.tokenURL'));
```suggestion
const idamUserManager = new IdamUserManager(endpoints.idamToken);
```

2022-05-16 11:59 UTC, abidfs submitted a review, later dismissed

2022-05-16 13:16 UTC, abidfs approved these changes

2022-05-17 08:34 UTC, pankajhmcts approved these changes

2022-05-17 08:35 UTC, merged