Adop 101 eligibility
hmcts/adoption-web pull request #58
Opened 2021-12-14 09:53 UTC by dilipsamrahmcts

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

https://tools.hmcts.net/jira/browse/ADOP-183

Added new eligibility screens plus unit tests

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [ ] No

2021-12-14 14:08 UTC, nraghu32 submitted a review, later dismissed

2021-12-14 14:09 UTC, abidfs requested changes
minor changes

2021-12-14 14:13 UTC, abidfs requested changes
minor changes

2021-12-14 14:13 UTC, abidfs commented on src/main/steps/eligibility/married/content.test.ts
>  describe('eligibility content', () => {
```suggestion
describe('married content', () => {
```

2021-12-14 14:13 UTC, abidfs commented on src/main/steps/eligibility/under-18/content.test.ts
>  describe('eligibility content', () => {
```suggestion
describe('under-18 content', () => {
```

2021-12-14 14:13 UTC, abidfs commented on src/main/steps/eligibility/under-21/content.test.ts
> +describe('eligibility content', () => {
```suggestion
describe('under-21 content', () => {
```

2021-12-15 09:04 UTC, abidfs approved these changes

2021-12-15 09:37 UTC, merged