Modified the dependencies version
hmcts/adoption-web pull request #627
Opened 2022-07-19 10:48 UTC by priteshkr

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### Change description

### JIRA link

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [ ] No

2022-07-19 17:04 UTC, sairamkantheti1 approved these changes

2022-07-19 22:32 UTC, pankajhmcts approved these changes

2022-07-19 22:33 UTC, pankajhmcts requested changes
Do not merge for now

2022-07-20 10:01 UTC, pankajhmcts approved these changes

2022-07-20 10:45 UTC, priteshkr commented
Closing this Pull Request as the same dependencies are not found to be vulnerable in subsequent nightly pipelines. So no need to push the changes

2022-07-20 10:45 UTC, closed without merging