Fpet 135 : Google Analytics Fixes
hmcts/adoption-web pull request #719
Opened 2022-08-26 10:04 UTC by priteshkr

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### Change description

### JIRA link

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [ ] No

2022-08-26 22:39 UTC, pankajhmcts requested changes
Once QA approved the changes, please let us know

2022-09-01 11:41 UTC, pankajhmcts requested changes
@rajatkgupta29 @mohitvijay45 @ShakiraKP Please reveiw the PR.

2022-09-01 11:55 UTC, rajatkgupta29 approved these changes

2022-09-01 12:24 UTC, mohitvijay45 approved these changes

2022-09-01 15:39 UTC, priteshkr commented
> @rajatkgupta29 @mohitvijay45 @ShakiraKP Please reveiw the PR.

Rajat and Mohit have approved. @pankajhmcts Please approve

2022-09-01 15:48 UTC, pankajhmcts approved these changes

2022-09-01 16:57 UTC, merged